### ISSUE TITLE
Tagbar

### ISSUE THREAD

**Issue by qJkee** [farazdagi/vim-go-ide#10]
After installation tag bar is aways empty
added 
let g:tagbar_ctags_bin = '/usr/local/bin/ctags' to plugins.vim but still no effect
![screen shot 2016-06-19 at 8 37 47 am](https://cloud.githubusercontent.com/assets/13433317/16175516/858c8c92-3601-11e6-975e-28a587e881c4.png)

**Comment by osleg** [comment]
The tagbar for go uses gotag, make sure you ran :GoInstallBinaries first time you launch vim to ensure that you have the correct binary.... and ensure it's in $PATH
