### ISSUE TITLE
Pathogen dependency

### ISSUE THREAD

**Issue by sungwoncho** [farazdagi/vim-go-ide#12]
I did not have pathogen installed on my machine, and was not able to run vim-go-ide after a fresh install.

After installing Pathogen, it works now. I could specify the dependency to the README if you want.

**Comment by farazdagi** [comment]
Feel free to supply pull request 😄

**Comment by linuxus** [comment]
I get this error when I try this plugin
~$ vim -u ~/.vimrc.go
Error detected while processing /home/abdi/.vim_go_runtime/vimrc/plugins.vim:
line    2:
E117: Unknown function: pathogen#infect
line    3:
E117: Unknown function: pathogen#infect
line    4:
E117: Unknown function: pathogen#helptags
Press ENTER or type command to continue

**Comment by vimalk78** [comment]
how to install pathogen ?

i am also getting same error

**Comment by vimalk78** [comment]
to install pathogen

mkdir -p ~/.vim/autoload ~/.vim/bundle 
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

**Comment by linuxus** [comment]
Thanks @vimalk78 for this tip... (fixed the pathogen issue) clearly the instruction on the document did not include this and assumption was made that all the plugins will be loaded with the clone of this repo.

Regards.
