### ISSUE TITLE
Error when running vim -u ~/.vimrc.go

### ISSUE THREAD

**Issue by linuxus** [farazdagi/vim-go-ide#13]
Here is what I get on new install of vim in Ubuntu 12.04 and cloning this repo
Error detected while processing /home/abdi/.vim_go_runtime/vimrc/plugins.vim:
line    2:
E117: Unknown function: pathogen#infect
line    3:
E117: Unknown function: pathogen#infect
line    4:
E117: Unknown function: pathogen#helptags
Press ENTER or type command to continue

**Comment by rosshambrick** [comment]
I'm getting the same error after a new install on OSX

**Comment by rosshambrick** [comment]
This seems to be a duplicate of #12.  I was able to fix this exact problem with an install of pathogen.

```
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
```

**Comment by farazdagi** [comment]
https://github.com/farazdagi/vim-go-ide/pull/14
