### ISSUE TITLE
Runtime error fresh install ubuntu 16.04

### ISSUE THREAD

**Issue by andrewcheny** [farazdagi/vim-go-ide#19]
I installed vim after run the install script

 vim -u ~/.vimrc.go
Error detected while processing /home/andrew/.vim_go_runtime/vimrc/plugins.vim:
line    2:
E117: Unknown function: pathogen#infect
line    3:
E117: Unknown function: pathogen#infect
line    4:
E117: Unknown function: pathogen#helptags
Press ENTER or type command to continue

**Comment by eplanit** [comment]
I get the same error in Ubuntu 14.04, but vim was installed (and used) previously.

**Comment by ghost** [comment]
same here - unusable like this

**Comment by cdmoye** [comment]
Do you guys have  pathogen installed? If not, you need it.

**Comment by ghost** [comment]
Yes I had it installed. Meantime I got an go with vi environment running without vim-go-ide.
I think the point is that you have to install and ->> configure. Purely install it does not help. So a better hint there might be helpfull here.

**Comment by lylex** [comment]
Seems like that pathogen is not well loaded.
Try to add the following at the beginning of /home/andrew/.vim_go_runtime/vimrc/plugins.vim:

`set nocp`
`set rtp+=~/.vim/autoload/pathogen.vim`

**Comment by ps23** [comment]
@farazdagi This can be closed now, README clearly outlines the need to install  pathogen into the standard vim setup: https://github.com/farazdagi/vim-go-ide#12-install-pathogen

**Comment by farazdagi** [comment]
That's right, thanks.
