### ISSUE TITLE
What about tags?

### ISSUE THREAD

**Issue by liuhewei** [farazdagi/vim-go-ide#2]
Actually it's not an issue report but a suggestion. Your work is very useful, so thanks for this sharing firstly :) But, what about the tag-list? I want to see the functions, packages, variables showing on right or left side, for example, just use **tagbar** as suggested in vim-go. I wonder why this feature is missed in your work...

**Comment by farazdagi** [comment]
Nice suggestion. I will definitely look into this. Thanks!

**Comment by icochico** [comment]
Great work!

**Comment by farazdagi** [comment]
done: https://github.com/farazdagi/vim-go-ide/commit/26581ac801a07bded4d13460db7464ef3962e314

For those who will want to use it please note that you need to install exuberant ctags (simple `brew install ctags-exuberant` on OSX)
