### ISSUE TITLE
colorscheme

### ISSUE THREAD

**Issue by n1ce37** [farazdagi/vim-go-ide#33]
how can I use your colorscheme. I don't find it in the internet.

**Comment by Liberxue** [comment]
![image](https://user-images.githubusercontent.com/5831248/54477376-24907880-4842-11e9-87b2-e259733442af.png) You can to deal with  colorscheme @n1ce37

**Comment by n1ce37** [comment]
> ![image](https://user-images.githubusercontent.com/5831248/54477376-24907880-4842-11e9-87b2-e259733442af.png) You can to deal with colorscheme @n1ce37

**Comment by n1ce37** [comment]
> ![image](https://user-images.githubusercontent.com/5831248/54477376-24907880-4842-11e9-87b2-e259733442af.png) You can to deal with colorscheme @n1ce37

thanks， now i use vscode for coding。
